[package]
name = "oberon"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.12.3"
regex = "1.10.3"
tokio = { version = "1.36.0", features = ["full"] }

[build-dependencies]
prost-build = "0.12.3"
